<?php
declare(strict_types=1);

return [
    'en' => [
        'week52' => [
            'kicker' => 'Free savings challenge calculator',
            'title' => '52 Week Savings Challenge: save €1,378 in one year',
            'intro' => 'Start with €1 in week one, add €1 each week and finish with €52 in week 52. The complete challenge adds up to €1,378 without requiring one large deposit.',
            'inputLabel' => 'Weekly increase',
            'totalLabel' => 'Total after 52 weeks',
            'frequencyLabel' => 'Contributions',
            'frequencyValue' => '52 weekly deposits',
            'tableTitle' => '52 week savings challenge table',
            'tableIntro' => 'Change the weekly increase to adapt every contribution and the final goal to your budget.',
            'headers' => ['Week', 'Save this week', 'Total saved'],
            'sections' => [
                ['How the 52 week savings challenge works', 'The classic version increases the amount gradually: €1, €2, €3 and so on. Adding the numbers from 1 to 52 produces a total of €1,378. You can start with any weekly increase; a €0.50 step reaches €689, while a €2 step reaches €2,756.'],
                ['Make the challenge easier to maintain', 'If the largest contributions fall at a difficult time of year, complete the table in reverse or choose weeks out of order. The habit matters more than the sequence. SaveTempo lets you use an increasing or random pattern and mark each contribution when you actually save it.'],
                ['Where should the money go?', 'Keep the money wherever you choose: a bank savings account, cash envelope or physical savings box. SaveTempo never holds or moves funds; it only helps you plan the schedule and record progress locally on your Android device.'],
            ],
            'ctaTitle' => 'Track the 52 week challenge automatically',
            'ctaBody' => 'Create the plan in SaveTempo, see what is due today, enable optional local reminders and mark every contribution at your own pace.',
        ],
        'day365' => [
            'kicker' => 'Daily savings challenge calculator',
            'title' => '365 Day Savings Challenge: save €667.95 one day at a time',
            'intro' => 'Save €0.01 on day one, €0.02 on day two and increase the amount by one cent each day. After 365 daily contributions, the total is €667.95.',
            'inputLabel' => 'Daily increase',
            'totalLabel' => 'Total after 365 days',
            'frequencyLabel' => 'Contributions',
            'frequencyValue' => '365 daily deposits',
            'tableTitle' => 'Monthly milestones for the 365 day challenge',
            'tableIntro' => 'Use these month-end totals to understand how the increasing daily challenge grows during the year.',
            'headers' => ['Month', 'Last challenge day', 'Total saved'],
            'months' => ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
            'sections' => [
                ['How the 365 day savings challenge works', 'The amount rises by the same small step every day. With a one-cent increase, the final daily contribution is €3.65 and the full-year total is €667.95. The calculator also supports a different step when your target is higher or lower.'],
                ['Build a daily habit without losing flexibility', 'Daily challenges work best when checking progress is easy. If you miss a day, record it as pending and catch up when it suits you. SaveTempo shows today’s contribution and keeps the schedule visible without connecting to a bank.'],
                ['Use reminders as a prompt, not a payment instruction', 'Optional reminders are scheduled locally on your device. They can bring you back to the relevant contribution, but they never execute a transfer or verify that money moved.'],
            ],
            'ctaTitle' => 'Keep all 365 contributions organized',
            'ctaBody' => 'SaveTempo gives the daily challenge a calendar, progress states and optional reminders while your financial data stays on your device.',
        ],
        'challengeApp' => [
            'kicker' => 'Savings challenge app for Android',
            'title' => 'Plan and track a savings challenge without connecting your bank',
            'intro' => 'SaveTempo is an Android savings challenge app for 52-week, 365-day and custom goals. It turns a target into scheduled contributions and lets you record progress privately.',
            'features' => [
                ['Choose a proven challenge', 'Start with a 52-week or 365-day schedule, then select an increasing or random pattern.'],
                ['Create a custom tracker', 'Define the amount, dates, currency and pace that fit your own savings goal.'],
                ['See what is due today', 'Review today’s contributions, pending savings and active plans from one calm home screen.'],
                ['Keep data local', 'SaveTempo has no bank connection, advertising, account requirement or cloud sync.'],
                ['Use optional reminders', 'Local notifications can take you to the correct contribution without moving money.'],
                ['Track real progress', 'Mark contributions as saved, partial or pending and review the plan in a calendar.'],
            ],
            'sections' => [
                ['What should a savings challenge app do?', 'A useful tracker should make the next action obvious, preserve the history of completed contributions and adapt when real life interrupts the schedule. It should not pretend to be a bank account or obscure where your money is held.'],
                ['SaveTempo’s privacy boundary', 'Your plan names, amounts, schedules and progress remain locally on the Android device. SaveTempo does not access bank accounts, transfer funds or collect in-app analytics.'],
                ['Which challenge should you choose?', 'Choose the 52-week challenge for a gradual weekly rhythm, the 365-day challenge for a small daily habit, or a custom plan when you already know the target and deadline.'],
            ],
            'ctaTitle' => 'Start your savings challenge on Android',
            'ctaBody' => 'Download SaveTempo from Google Play and create your first active savings plan for free.',
        ],
    ],
    'es' => [
        'week52' => [
            'kicker' => 'Calculadora gratuita de ahorro',
            'title' => 'Reto de ahorro de 52 semanas: ahorra 1.378 € en un año',
            'intro' => 'Empieza con 1 € la primera semana, añade 1 € cada semana y termina con 52 € en la semana 52. El reto completo suma 1.378 € sin exigir un único ingreso grande.',
            'inputLabel' => 'Incremento semanal',
            'totalLabel' => 'Total después de 52 semanas',
            'frequencyLabel' => 'Aportaciones',
            'frequencyValue' => '52 ingresos semanales',
            'tableTitle' => 'Tabla del reto de ahorro de 52 semanas',
            'tableIntro' => 'Cambia el incremento semanal para adaptar cada aportación y el objetivo final a tu presupuesto.',
            'headers' => ['Semana', 'Ahorra esta semana', 'Total ahorrado'],
            'sections' => [
                ['Cómo funciona el reto de ahorro de 52 semanas', 'La versión clásica aumenta la cantidad poco a poco: 1 €, 2 €, 3 € y así sucesivamente. La suma de los números del 1 al 52 da un total de 1.378 €. Puedes empezar con cualquier incremento; con 0,50 € alcanzarás 689 € y con 2 € llegarás a 2.756 €.'],
                ['Haz que el reto sea fácil de mantener', 'Si las aportaciones más altas coinciden con una época complicada, completa la tabla al revés o elige las semanas en otro orden. El hábito importa más que la secuencia. SaveTempo permite usar un patrón creciente o aleatorio y marcar cada aportación cuando realmente la ahorras.'],
                ['Dónde guardar el dinero', 'Guarda el dinero donde prefieras: una cuenta de ahorro, un sobre de efectivo o una hucha física. SaveTempo nunca custodia ni mueve fondos; solo ayuda a planificar el calendario y registrar el progreso localmente en Android.'],
            ],
            'ctaTitle' => 'Registra automáticamente el reto de las 52 semanas',
            'ctaBody' => 'Crea el plan en SaveTempo, consulta qué toca hoy, activa recordatorios locales opcionales y marca cada aportación a tu propio ritmo.',
        ],
        'day365' => [
            'kicker' => 'Calculadora del reto diario',
            'title' => 'Reto de ahorro de 365 días: ahorra 667,95 € poco a poco',
            'intro' => 'Ahorra 0,01 € el primer día, 0,02 € el segundo y aumenta un céntimo cada día. Después de 365 aportaciones diarias, el total es de 667,95 €.',
            'inputLabel' => 'Incremento diario',
            'totalLabel' => 'Total después de 365 días',
            'frequencyLabel' => 'Aportaciones',
            'frequencyValue' => '365 ingresos diarios',
            'tableTitle' => 'Objetivos mensuales del reto de 365 días',
            'tableIntro' => 'Estos totales al final de cada mes muestran cómo crece el reto diario durante el año.',
            'headers' => ['Mes', 'Último día del reto', 'Total ahorrado'],
            'months' => ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
            'sections' => [
                ['Cómo funciona el reto de ahorro de 365 días', 'La cantidad aumenta cada día con el mismo pequeño incremento. Con un céntimo, la última aportación es de 3,65 € y el total anual alcanza 667,95 €. La calculadora también admite otro incremento si tu objetivo es mayor o menor.'],
                ['Crea un hábito diario sin perder flexibilidad', 'Los retos diarios funcionan mejor cuando revisar el progreso es sencillo. Si un día no puedes ahorrar, déjalo pendiente y recupéralo cuando te venga bien. SaveTempo muestra la aportación de hoy y mantiene visible el calendario sin conectarse al banco.'],
                ['Usa los avisos como recordatorio, no como orden de pago', 'Los recordatorios opcionales se programan localmente en el dispositivo. Pueden llevarte hasta la aportación correspondiente, pero nunca ejecutan transferencias ni verifican movimientos de dinero.'],
            ],
            'ctaTitle' => 'Mantén organizadas las 365 aportaciones',
            'ctaBody' => 'SaveTempo añade calendario, estados de progreso y recordatorios opcionales al reto diario mientras tus datos permanecen en el dispositivo.',
        ],
        'challengeApp' => [
            'kicker' => 'App de retos de ahorro para Android',
            'title' => 'Planifica y registra un reto de ahorro sin conectar tu banco',
            'intro' => 'SaveTempo es una app Android para retos de ahorro de 52 semanas, 365 días y objetivos personalizados. Convierte una meta en aportaciones programadas y permite registrar el progreso de forma privada.',
            'features' => [
                ['Elige un reto conocido', 'Empieza con un calendario de 52 semanas o 365 días y selecciona un patrón creciente o aleatorio.'],
                ['Crea un registro personalizado', 'Define la cantidad, fechas, moneda y ritmo que encajan con tu propio objetivo.'],
                ['Consulta qué toca hoy', 'Revisa aportaciones de hoy, ahorros pendientes y planes activos desde una pantalla clara.'],
                ['Mantén los datos en local', 'SaveTempo no tiene conexión bancaria, publicidad, cuenta obligatoria ni sincronización cloud.'],
                ['Activa avisos opcionales', 'Las notificaciones locales pueden llevarte a la aportación correcta sin mover dinero.'],
                ['Registra el progreso real', 'Marca aportaciones como ahorradas, parciales o pendientes y revisa el plan en el calendario.'],
            ],
            'sections' => [
                ['Qué debe aportar una app de retos de ahorro', 'Un buen registro debe dejar claro el siguiente paso, conservar el historial de aportaciones completadas y adaptarse cuando la vida interrumpe el calendario. No debe fingir que es una cuenta bancaria ni ocultar dónde se guarda el dinero.'],
                ['El límite de privacidad de SaveTempo', 'Los nombres de planes, cantidades, calendarios y progreso permanecen localmente en el dispositivo Android. SaveTempo no accede a cuentas bancarias, no transfiere fondos y no recopila analítica dentro de la app.'],
                ['Qué reto elegir', 'Elige el reto de 52 semanas para un ritmo semanal progresivo, el de 365 días para crear un pequeño hábito diario o un plan personalizado si ya conoces el objetivo y la fecha límite.'],
            ],
            'ctaTitle' => 'Empieza tu reto de ahorro en Android',
            'ctaBody' => 'Descarga SaveTempo en Google Play y crea gratis tu primer plan de ahorro activo.',
        ],
    ],
];
